### ISSUE TITLE
hrosailing import error

### ISSUE THREAD

**Issue by m-h-w** [hrosailing/hrosailing#114]
I get the following error when trying to use the hrosailing package, imported with rye.

>>> import hrosailing.plotting as plot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mathewwaite/Code/polar/.venv/lib/python3.9/site-packages/hrosailing/__init__.py", line 68, in <module>
    import hrosailing.pipeline
  File "/Users/mathewwaite/Code/polar/.venv/lib/python3.9/site-packages/hrosailing/pipeline/__init__.py", line 7, in <module>
    from .extensions import (
  File "/Users/mathewwaite/Code/polar/.venv/lib/python3.9/site-packages/hrosailing/pipeline/extensions.py", line 11, in <module>
    import hrosailing.polardiagram as pol
  File "/Users/mathewwaite/Code/polar/.venv/lib/python3.9/site-packages/hrosailing/polardiagram/__init__.py", line 8, in <module>
    from ._polardiagrammultisails import PolarDiagramMultiSails
  File "/Users/mathewwaite/Code/polar/.venv/lib/python3.9/site-packages/hrosailing/polardiagram/_polardiagrammultisails.py", line 8, in <module>
    from ._polardiagramtable import PolarDiagramTable
  File "/Users/mathewwaite/Code/polar/.venv/lib/python3.9/site-packages/hrosailing/polardiagram/_polardiagramtable.py", line 660, in <module>
    class _Resolution(enum.Enum):
  File "/Users/mathewwaite/.rye/py/cpython@3.9.19/lib/python3.9/enum.py", line 301, in __new__
    if canonical_member._value_ == enum_member._value_:
ValueError: operands could not be broadcast together with shapes (20,) (72,) 
>>> ^D

**To Reproduce / Minimal Example**
1. install python 3.9 with rye
2. rye add hro sailing
3. rye add the dependencies
4. start python
>>> import hrosailing.plotting as plot

**Comment by RobertSchueler** [comment]
Thanks for reporting. I will not be able to take a look soon (maybe in 2 to 3 weeks). What about you @rubbinduck ?

**Comment by rubbinduck** [comment]
The issue was already fixed in commit 24243f2 (see also issue #112 ). We just haven't uploaded the current version to pip yet.

**Comment by RobertSchueler** [comment]
Maybe it makes sense to release a patch version with this fix so no-one else runs into this error.

**Comment by rubbinduck** [comment]
It might make sense yes. I can do that tomorrow after i push a fix for a bug with newer matplotlib versions, so we can make a patch in one go and then we should be all gucci.

**Comment by m-h-w** [comment]
If you can do that itvwould be great.

Thanks!!

**Comment by rubbinduck** [comment]
Should be fixed as of commit 3251572 and is deployed to pypi as of release v0.11.1.

**Comment by m-h-w** [comment]
Thanks for this. I have tested it and the issue is resolved.
